# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5933d5e8a6567f8b54c7f23ff2d28c19a8f96220d33f3262e1aa3589696fc29087328e19e44fbd44e6dde3fe68d4deb58fee73eab3dfba010adae1f2854fafa6

staging:
  secret_key_base: a54d9fe11224dde1105bb82b0049c5a7b792e0e70eabeae1c4bd8c4140e3a1ef6e7dcc3577c470a03abc5a1aa76df0bc8ddcefd71c23fc0a93d8c1466169b1b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["DAKOTA_SECRET_KEY_BASE"] %>
